Repository jenkinsci/docker-java-api-plugin, pull requests merged in 2024-12, with the labels that each got.

#110 Use Commons Compress library plugin
  pom.xml
Labels: bug

#112 Move contribution guidelines into CONTRIBUTING page
  .gitpod.Dockerfile
  .gitpod.yml
  CONTRIBUTING.md
  README.md
Labels: documentation

#113 Use jenkins.baseline for plugin BOM version
  pom.xml
Labels: chore

#114 Check dependencies monthly
  .github/dependabot.yml
Labels: dependencies
